{"name": "test_put_invalid_data_status_code[request_data1]", "status": "passed", "description": "\n        Проверка статуса ответа метода PUT при запросе с невалидными данными.\n        Ожидаемый результат 400\n        ", "attachments": [{"name": "log", "source": "36715b24-b0e4-4145-9d28-640f0ff0d313-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "request_data", "value": "{'key': 'wrong'}"}], "start": 1591441674751, "stop": 1591441674760, "uuid": "33db6e21-7a4a-46cd-bc50-8d3bde569b19", "historyId": "43caddaa806db613649fa59f43ba52ec", "testCaseId": "4234cd3052612d52fa8b63503de09fec", "fullName": "tests.test_api_put.TestPut#test_put_invalid_data_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_put"}, {"name": "subSuite", "value": "TestPut"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "5340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_put"}]}