{"name": "test_put_invalid_data_status_code[request_data3]", "status": "passed", "description": "\n        Проверка статуса ответа метода PUT при запросе с невалидными данными.\n        Ожидаемый результат 400\n        ", "attachments": [{"name": "log", "source": "77aa9856-fe8f-40db-8e47-6c3c7e73159c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "request_data", "value": "{}"}], "start": 1591441674782, "stop": 1591441674790, "uuid": "9da9a87f-06d3-4cac-a562-1cf8e08511ee", "historyId": "c2a844bee435644ff88c814e9f2f41f2", "testCaseId": "4234cd3052612d52fa8b63503de09fec", "fullName": "tests.test_api_put.TestPut#test_put_invalid_data_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_put"}, {"name": "subSuite", "value": "TestPut"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "5340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_put"}]}