{"name": "test_put_invalid_data_status_code[request_data0]", "status": "passed", "description": "\n        Проверка статуса ответа метода PUT при запросе с невалидными данными.\n        Ожидаемый результат 400\n        ", "attachments": [{"name": "log", "source": "cc4c1b18-7829-457c-96f7-03e150b710b5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "request_data", "value": "{'value': 'wrong'}"}], "start": 1591441674736, "stop": 1591441674745, "uuid": "c08c510c-4b6a-42fd-88b6-ef273990aba7", "historyId": "cb46ce2c3e7eea9229172a2279e67847", "testCaseId": "4234cd3052612d52fa8b63503de09fec", "fullName": "tests.test_api_put.TestPut#test_put_invalid_data_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_put"}, {"name": "subSuite", "value": "TestPut"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "5340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_put"}]}