{"name": "test_put_invalid_data_status_code[request_data4]", "status": "passed", "description": "\n        Проверка статуса ответа метода PUT при запросе с невалидными данными.\n        Ожидаемый результат 400\n        ", "attachments": [{"name": "log", "source": "af8ef68b-e8b8-49b6-a92c-8ea22909bafd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "request_data", "value": "['key', 'value']"}], "start": 1591447258658, "stop": 1591447258666, "uuid": "9502b1e3-8668-43ed-9bf3-cf7366e11e26", "historyId": "b6c743bf1b365959cf0b034c93001841", "testCaseId": "4234cd3052612d52fa8b63503de09fec", "fullName": "tests.test_api_put.TestPut#test_put_invalid_data_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_put"}, {"name": "subSuite", "value": "TestPut"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "5837-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_put"}]}