{"name": "test_put_invalid_data_status_code[request_data1]", "status": "passed", "description": "\n        Проверка статуса ответа метода PUT при запросе с невалидными данными.\n        Ожидаемый результат 400\n        ", "attachments": [{"name": "log", "source": "0e3a1fc7-34f2-4b2b-bae0-f2a4b0421c31-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "request_data", "value": "{'key': 'wrong'}"}], "start": 1591447258608, "stop": 1591447258617, "uuid": "40b9be3f-7364-4e10-9b66-8f668af96255", "historyId": "43caddaa806db613649fa59f43ba52ec", "testCaseId": "4234cd3052612d52fa8b63503de09fec", "fullName": "tests.test_api_put.TestPut#test_put_invalid_data_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_put"}, {"name": "subSuite", "value": "TestPut"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "5837-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_put"}]}