{"name": "test_put_invalid_data_status_code[request_data3]", "status": "passed", "description": "\n        Проверка статуса ответа метода PUT при запросе с невалидными данными.\n        Ожидаемый результат 400\n        ", "attachments": [{"name": "log", "source": "97904ee2-d76b-46b8-9928-77e56224dfbf-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "request_data", "value": "{}"}], "start": 1591447258643, "stop": 1591447258650, "uuid": "3a8b1917-d295-4aeb-b076-d7142cc5da3a", "historyId": "c2a844bee435644ff88c814e9f2f41f2", "testCaseId": "4234cd3052612d52fa8b63503de09fec", "fullName": "tests.test_api_put.TestPut#test_put_invalid_data_status_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_put"}, {"name": "subSuite", "value": "TestPut"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "5837-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_put"}]}